[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=4c0c730a-3bed-4bce-8aa9-6bcda1219d29
Description=摆摊
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]


For 70
'==========以下是按键精灵录制的内容==========
MoveTo 586, 619
Delay 771
LeftClick 1
Delay 1000
MoveTo 474, 505
Delay 500
LeftClick 1
Delay 800
'==========以上是按键精灵录制的内容==========

Next
